pipeline {
    agent any

    stages {
        stage('Install') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Server') {
            steps {
                sh 'node app.js'
            }
        }
    }
}